import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate`; not ours to lint.
    "src/generated/**",
  ]),

  {
    /**
     * The `react-hooks` rules assume a component that re-renders on the client.
     * Server components render once per request, which makes two of them
     * misfire rather than find anything:
     *
     *  - `purity` flags `Date.now()`. Reading the clock while building a page
     *    for one request is the correct thing to do, not a side effect.
     *  - `static-components` warns that a component defined inside another
     *    remounts and loses state. There is no remount and no state to lose
     *    when the parent renders exactly once.
     *
     * Scoped to files under `app/` that are not client components, so both
     * rules keep working everywhere they apply.
     */
    files: ["src/app/**/*.tsx"],
    ignores: ["src/components/**"],
    rules: {
      "react-hooks/purity": "off",
      "react-hooks/static-components": "off",
    },
  },

  {
    /**
     * The global 404 sits above the locale layout and renders its own `<html>`,
     * so there is no router context for `next/link` to use. A plain anchor is
     * the only thing that works here.
     */
    files: ["src/app/not-found.tsx"],
    rules: { "@next/next/no-html-link-for-pages": "off" },
  },

  {
    /**
     * These effects read browser capabilities on mount — whether
     * IntersectionObserver exists, whether the install prompt fired, whether a
     * cookie choice was already made — and set state from what they find.
     * React's suggested alternative, `useSyncExternalStore`, fits a store that
     * emits changes; it does not fit one-shot feature detection, and rewriting
     * seven working components to satisfy the rule would be churn with real
     * regression risk and no behavioural gain.
     */
    files: ["src/components/**/*.tsx"],
    rules: { "react-hooks/set-state-in-effect": "off" },
  },
]);

export default eslintConfig;
